name: Run CocoaPods lint

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  cocoapods_lint:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Run CocoaPods lint
        run: |
          bundle exec pod spec lint